driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.7.16

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[afw]
    verifier:
      inspec_tests:
        - test/integration
    attributes:
      afw:
        rules:
          "Allow SSH":
            direction: in
            protocol: tcp
            user: root
            interface: all
            source: "0.0.0.0/0"
            dport: 22
